# Variables
OCAMLBUILD = ocamlbuild
TARGET = main.native

# Default target
all: build

# Build target
build:
	$(OCAMLBUILD) $(TARGET)

# Clean target
clean:
	$(OCAMLBUILD) -clean

.PHONY: all build clean
